FROM nvidia/cuda:12.2.0-devel-ubuntu22.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update -y

RUN apt install -y python3-pip wget ffmpeg git imagemagick dos2unix
RUN sed -i '91d' /etc/ImageMagick-6/policy.xml

EXPOSE 7414
ADD . /app
# ADD sadtalker_api /sadtalker // this is for remote intergration test
RUN pip install -qr requirements.txt
CMD ["/bin/bash", "run.sh"]
